@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
skinparam roundcorner 20
skinparam linetype polyline
skinparam linetype ortho
skinparam classBackgroundColor #wheat
skinparam nodesep 100
skinparam ranksep 200

class LauncherKingdomino{
    +{static} main( args:String[] )
}

package Utilities {
    class CSVReader{
        +CSVReader()
        {static}+readCSV(path:String):String[][]
    }

    class FontUtilities {
        +FontUtilities()
        {static}+setFont(path:String): Font
    }

}

package Model #salmon;line:red{

    class Game {
        {static}-instance:Game
        -Game()
        {static}+getInstance()
        +addGameMode(gameMode: GameMode)
        +factorHarmonyMode()
        +factorMiddleKingdom()
        +setNumberPlayer(strategy: NumberPlayerStrategy)
        +setTwoPlayers()
        +setThreePlayers()
        +setQuatroPlayers()
        +createPlayers(numberPlayer: Integer)
        +setCastlePlayer(index:Integer, x:Integer, y:Integer)
        +createDeck(numberPlayer: Integer)
        +getActualDominoes(): Collection<Domino>
        +putDominoOnTable()
        +sortDominoTable(n: Integer)
        +addObservers(observer: Observer)
        +notifyObservers()
    }

    interface Observer<<interface>>{
       +update(game:Game)
    }

    package Entities #indianred{
        Graph "0..*\n-_arrayTiles" *-> Tile : <<composed of>> >

        class Graph {
            +Graph()
            +setDomino(domino:Domino, x:Integer, y:Integer)
            +isPlaceAvailable(x:Integer, y:Integer):Boolean
            +setCastle(x:Integer, y:Integer, castle:Castle)

        }

        class King{
            {static}-_colorUsed: Collection<KINGCOLOR>
            {static}-_rand: Integer
            {static}-_size: Integer

            +King()
            +randomChose(): KINGCOLOR
        }


        Deck "-_listDominoes\n1..*" *-> Domino : <<composed of>> >


        class Deck{
            {static}-rand:Integer{readOnly}
            +Deck(numberPlayer: Integer)
            -removeDomino(iteration: Integer)
            -generateDomino(i:Integer, dataCSV:String[][])
            +getStack(): Collection<Domino>
            +sizeOfDeck(): Integer
            +shuffle()
            +giveADomino(): Domino
        }

        Domino "-_arrayTiles\n0..2" *-l-> Tile : <<has>> >
        class Domino {
           -id:Integer
           +Domino(id:Integer, tile1:Tile, tile2:Tile)
           -setTile(tile1:Tile, tile2:Tile)
           +isXX():Boolean
           +isXY():Boolean
           +getTile():Tile[][]
           +getId(): Integer
           +rotate()
        }

        class Tile{
           -_color:String
           -_crowns:Integer
           +Tile(suitColor, crownsSuit)
           +Tile()
           +setColorTile(color: String)
           +getCrowns() Integer
           +getColor(): String
        }

        Player "1\n-_graph" *--> Graph : > <<has>>
        Player "1\n-_king"*-> King : > <<has>>
        Player "1\n-_castle" *-l-> Castle : > <<has>>
        class Player {
            +Player()
            +initialiseGraph()
            +initialiseCastle()
            +setCastle(x: Integer, y:Integer)
            +getGraph(): Graph
        }

        class Castle extends Tile{
            +Castle(color: String)
        }

        enum KINGCOLOR {
            +PINK
            +YELLOW
            +GREEN
            +BLUE
        }
        Player "1\n{static}_colorUsed" *--> KINGCOLOR: > <<has>>


    }


    package Set #indianred {

        class NumberPlayer{
            -_numberPlayers: Integer
            +NumberPlayer()
            +setStrategyPlayer(strategy: NumberPlayerStrategy)
            +executeStrategy()
            +setNumberPlayers(players: Integer)
            +getNumberPlayers(): Integer
            +getTwoPlayers(): Duo
            +getThreePlayers(): Trio
            +getQuatroPlayers(): Quatro
         }

        NumberPlayer o--> "-_strategy\n1"NumberPlayerStrategy: > <<choose>>

        package Number{
            class Duo implements NumberPlayerStrategy
            {
                +setNumberPlayers(player: NumberPlayer)
            }

            class Trio implements NumberPlayerStrategy
            {
                +setNumberPlayers(player: NumberPlayer)
            }

            class Quatro implements NumberPlayerStrategy
            {
                +setNumberPlayers(player: NumberPlayer)
            }
        }

        GameModeFactory ..> GameMode : <<use>> >

        class GameModeFactory{
            +GameModeFactory()
            +createMiddleKingdom(): GameMode
            +createHarmony(): GameMode
            +createMightyDuel(): GameMode
        }

        abstract GameMode<<abstract>>{
            -_isSevenSize: Boolean
            -_numberBonus: Integer
            +executeGameMode()
            {abstract}+numberBonus(): Integer
            {abstract}+sizeGraph(): Boolean
        }


            package mode{
                class MiddleKingdom extends GameMode{
                    +numberBonus(): Integer
                    +sizeGraph(): Boolean
                }

                class Harmony extends GameMode{
                    +numberBonus(): Integer
                    +sizeGraph(): Boolean
                }

                class MightyDuel extends GameMode{
                    +numberBonus(): Integer
                    +sizeGraph(): Boolean
                }

                GameModeFactory ..> MiddleKingdom: <<use>> >
                GameModeFactory ..> Harmony: <<use>> >
                GameModeFactory ..> MightyDuel: <<use>> >
            }

    }

    interface NumberPlayerStrategy<<interface>>{
        +strategyPlayer()
    }
}

package View #lightgreen;line:green{
    Window ..> KingDominoStart : <<use>> >
    KingDominoStart ..> KingDominoGame : <<use>> >
    KingDominoGame ..> KingDominoEnd: <<use>> >

    class Window implements Observer
    {
        +Window(game:Game, controller:Controller)
        {override}+update(observer:Observer)
        {override}+rotationDomino(game:Game)
    }

    class KingDominoStart implements Observer
    {
        +KingDominoStart()
        {override}+update(game:Game)
        {override}+rotationDomino(game:Game)
    }

    class KingDominoGame implements Observer
    {
        -_indexDominoClicked: Integer
        -_unicodeCrown: String
        -_castleIsSet: Boolean[]
        -_mapGraphPlayer: Dictionnary<Integer, Button[][]>

        +KingDominoGame()
        {override}+update(game:Game)
        {override}+rotationDomino(game:Game)
        +setCrownRotation()
        +createDominoes()
        +createGraph()
        setBackgroudDominoGraph(x:Integer, y:Integer, condition:Boolean)
        +putDominoRotate()
        +setTextInformation(text: String)
        +allCastleSet()
    }

    class KingDominoEnd implements Observer
    {
        +KingDominoEnd()
        {override}+update(game:Game)
        {override}+rotationDomino(game:Game)
    }
}

package Controller #gold;line:goldenrod {

    class Controller{
        +Controller(game: Game)
        +instanciateDeck(numberPlayer: Integer)
        +instanciatePlayer(numberPlayer: Integer)
        +putDominoOnTable()
        +switchToDuo()
        +switchToTrio()
        +switchToQuatro()
        +callHarmony()
        +callMiddleKingdom()
        +setCastle(index:Integer, x:Integer, y:Integer)
        +addObserver(observer: Observer)
    }

}

Window -> Window : "1\n{static}#instance"
Window .> Controller : "1\n #_controller\t"<<use>> >
Window .> Game : "1\n #_game" <<use>> >
Window "1\n #_fontGermania" .> FontUtilities : <<use>>
Window "1\n #_fontTimeless" .> FontUtilities : <<use>>

KingDominoStart "1\n-_window"*--> Window
KingDominoGame "1\n-_window"*-> Window
KingDominoEnd "1\n-_window"*-> Window

LauncherKingdomino ..> Window : <<create>> >
LauncherKingdomino ..> Controller : <<create>> >
LauncherKingdomino .> Game : <<create>> >

Game "1\n{static}instance" --> Game
Game "1\n-_listGameMode" *--> GameMode : <<has>> >
Game "1\n-_numberplayer" *--> NumberPlayer : <<has>> >
Game "1\n-_deck" *-> Deck : <<has>> >
Game "2..4\n-_listPlayers" *--> Player : <<has>> >
Game o..> NumberPlayerStrategy : <<set>> >
Game *-l-> Observer : "0..*\n-_observer"<<notify>> >
Game *--> GameModeFactory : "1..2\n_factoryGameMode"<<has>> >
Game *--> Domino : "4\n_actualDominoes"<<has>> >

NumberPlayer ..> Duo : <<use>> >
NumberPlayer ..> Trio : <<use>> >
NumberPlayer ..> Quatro : <<use>> >


Controller "1\n-_game"..> Game : <<use>> >
Controller o.> Observer : <<use>> >

King *-r-> "1\n-_kingColor" KINGCOLOR : <<has>> >

Deck .d.> CSVReader : <<use>> >

@enduml
