@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods


class Tile{
    -right:Ground
    -left:Ground
    -number:Integer
}
class King{
    -color:

}

class Player{

}

class Board{
    -x:Integer
    -y:Integer
}

Player *--> King : "-kings\n1..2"
Player *-> Board : "-board\n1"

class Ground{
    -color
    -crown:Integer
}

class Castle{
}

class VariantContext{

}

interface Variant{

}

class Variant1 implements Variant{
}



@enduml