@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods


class Main{
}



package models{

    class King{
        -color:
    }

    class Player{

    }

    class Board{
        -x:Integer
        -y:Integer
        -isPossible:Boolean
    }

    class Ground{
        -crown:Integer
    }


    interface Positionable{
    }

    class Castle implements Positionable{
    }

    class Tile implements Positionable{
        -right:Ground
        -left:Ground
        -number:Integer
    }

    enum Color{
        YELLOW
        DARK GREEN
        LIGHT GREEN
        BLUE
        BROWN
        BLACK
    }
}

Ground *-> Color : "-"

Player *--> King : "-kings\n1..2"
Player *-> Board : "-board\n1"
Tile *--> Ground :  "-left\n1\n-right\n1"


class VariantContext{

}

interface Variant{

}

class Variant1 implements Variant{
}


package Controller{

}


package View{

}



@enduml